version: '3.7'
services:
  acme:
    build:
      context: .
    environment:
      PGDATABASE: acme_dev
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: acme_db
    command: sh -c "mix phx.server"
    ports:
      - 4000:4000
    container_name: acme
    networks:
      - acme_default

  acme_db:
    image: postgres:15.1
    volumes:
      - ./data:/var/lib/postgresql/data
      - '.:/share'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    container_name: acme_db
    networks:
      - acme_default

networks:
  acme_default:
    driver: bridge
    name: acme_default
